### ISSUE TITLE
Is Versionista free?

### ISSUE THREAD

**Issue by KrzysztofMadejski** [patcon/awesome-website-change-monitoring#1]
I haven't found any price plan on Versionista website. Is it free? What limitations does it have?

Maybe we could add such details into the spreadsheet?

**Comment by KrzysztofMadejski** [comment]
Now that I've registered:
- 7/30 days free trial `Try a free 7 day trial of any paid plan / Experience the full power of Versionista with a 30 day free trial.`

Some plans:
- Mini: Monitor 20 URLs and archive 10 versions per URL. - 19$
- Monitor 400 URLs and archive 20 versions per URL. - 99 $/month
- Monitor 1,200 URLs and archive 50 versions per URL. 249 $/month
- Enterprise Premium 10k - Monitor 10,000 URLs and archive 50 versions per URL. - 1250$ / month

**Comment by patcon** [comment]
@KrzysztofMadejski Is there a public-facing URL for that info? (I realize you had to sign up, but thinking maybe the page is just not linked.)

If so, maybe we could add a spreadsheet column for this sort of detail, and link to it for full details?

**Comment by KrzysztofMadejski** [comment]
There is no public-facing URL. You get that info only after you register.

**Comment by patcon** [comment]
OK, self-hosted: https://hackmd.io/IYBgzARgjMDGwFoCsATALAMwZmDhRRAXGDAA4oowwMoBOIA=?view

Mind if I get the url (though private) just to provide that anyhow?

**Comment by patcon** [comment]
Anyhow, added a pricing column with a link to some urls for now :) Thanks @KrzysztofMadejski 

If you have time to find a url, I'll source it in hackmd pad

**Comment by KrzysztofMadejski** [comment]
Thanks @patcon! https://versionista.com/subscribe is the link
