### ISSUE TITLE
Add "website-change-monitor" to the "Open Source" list

### ISSUE THREAD

**Issue by JuanmaMenendez** [patcon/awesome-website-change-monitoring#8]
Add [Website Change Monitor](https://github.com/JuanmaMenendez/website-change-monitor) to the "Open Source" list.

**Repo Description**
[Website Change Monitor](https://github.com/JuanmaMenendez/website-change-monitor) : A small web app written in Node.js to monitor specific changes on a web page and get email and Slack notifications.

**Comment by lightandluck** [comment]
Closed via https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring/commit/daf29295b7e26100e4e95d95ba72a7b3751af717
